[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scAnalysis"
version = "0.1.4"
description = "A single-cell analysis pipeline."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "h5py",
    "statsmodels",
    "umap-learn",
    "leidenalg",
    "louvain",
    "igraph",
    "plotly"
]